# Custom Language File for Launcher Customizer

[ejs.app]
title = "상현의놀이터"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/SHPlayGround"
mediaTwitterURL = "#"
mediaInstagramURL = "https://www.instagram.com/sang_n0w/"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/SHPlayGround"
supportLink = "https://github.com/CustomLauncherLab/SHPlayGround/issues"

[ejs.welcome]
welcomeHeader = "상현의놀이터를 즐겨주셔서 감사합니다."
welcomeDescription = "1인 개발인 만큼 미흡한 점도 많고 오류가 있을 수 있습니다.<br>문제가 생긴다면 디스코드 채널을 통해 바로 문의 부탁드립니다."
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
